//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int DISH_ID { get; set; }
        public string DISH_NAME { get; set; }
        public int CATEGORY_ID { get; set; }
        public int PRICE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_TIMESTAMP { get; set; }
        public string UPDATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_TIMESTAMP { get; set; }
    
        public virtual category category { get; set; }
    }
}
