'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class RestaurantManagementEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=RestaurantManagementEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property categories() As DbSet(Of category)
    Public Overridable Property menus() As DbSet(Of menu)
    Public Overridable Property register_user() As DbSet(Of register_user)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)

End Class
