'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class menu
    Public Property DISH_ID As Integer
    Public Property DISH_NAME As String
    Public Property CATEGORY_ID As Integer
    Public Property PRICE As Integer
    Public Property CREATED_BY As String
    Public Property CREATED_TIMESTAMP As Nullable(Of Date)
    Public Property UPDATED_BY As String
    Public Property UPDATED_TIMESTAMP As Nullable(Of Date)

    Public Overridable Property category As category

End Class
