'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class register_user
    Public Property USER_ID As Integer
    Public Property EMAIL_ID As String
    Public Property FIRST_NAME As String
    Public Property LAST_NAME As String
    Public Property GENDER As String
    Public Property PASSWORD As String
    Public Property PHONE As String

End Class
